### ISSUE TITLE
Replace difference with diff?

### ISSUE THREAD

**Issue by lunaryorn** [calder/rust-goldenfile#4]
`cargo audit` reports that `difference` is unmaintained:

```
Crate:  difference
Title:  difference is unmaintained
Date:   2020-12-20
URL:    https://rustsec.org/advisories/RUSTSEC-2020-0095
```

pretty-assertions [switched to the diff crate](https://github.com/colin-kiegel/rust-pretty-assertions/blob/main/CHANGELOG.md#changed); would this work for this crate as well?

**Comment by calder** [comment]
It should, yeah! PRs welcome!

**Comment by lunaryorn** [comment]
I can make one for sure, but will you review and release it soonish? 

I am sorry, and I mean no offense, but you took some time to reply with just a fairly standard answer, so please do forgive me for being a bit sceptical 😔

**Comment by lunaryorn** [comment]
All right then 🙂
