### ISSUE TITLE
Thoughts on best practices for line endings?

### ISSUE THREAD

**Issue by SUPERCILEX** [calder/rust-goldenfile#8]
I'm currently using git attributes to keep LF endings on Windows, but I'm wondering if the text differ should ignore LF/CTLF differences by default. WDYT?

**Comment by calder** [comment]
We probably want to keep strict diffs the default, but feel free to submit a PR to add a line-ending-agnostic differ!

**Comment by calder** [comment]
Closing for now but looking forward to a PR!
